In [2]:
import pandas as pd
import numpy as np
import matplotlib as mp

In [3]:
print(np.__version__)
print(pd.__version__)
print(mp.__version__)

1.24.4
2.1.1
3.8.0


In [5]:
print("hello world")

a="moro Tampere"
a

hello world


'moro Tampere'

Numpy arrays vs Python list
Numpy is fast, convient, less memory



In [6]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
a[1]

2

In [8]:
import time
import sys

In [12]:
b=range(1000)
print(sys.getsizeof(5)*len(b))

28000


In [14]:
c = np.arange(1000)
print(c.size*c.itemsize)

8000


In [15]:
size = 100000

In [16]:
L1 = range(size)
L2 = range(size)
A1 = np.arange(size)
A2 = np.arange(size)

In [18]:
start =time.time()
result = [(x+y) for x,y in zip(L1, L2)]
result = [(x+y) for x,y in zip(L1,L2)]
#print(result)
print("python list took: ", (time.time()-start)*1000)


python list took:  71.1522102355957


In [19]:
start =time.time()
result = A1 + A2
print("numpy array took: ", (time.time()-start)*1000)

numpy array took:  7.673025131225586


In [22]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
a.ndim

2

In [24]:
a.itemsize

8

In [25]:
a.shape

(3, 2)

In [28]:
a = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [29]:
a.itemsize

8

In [30]:
a.shape

(3, 2)

In [32]:
a = np.array([[1,2],[3,4],[5,6]], dtype=np.complex_)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [33]:
a.dtype

dtype('complex128')

In [35]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
print("Concatenation example:")
print(np.char.add(["moro", "moikka"], ["abd", "edf"]))

Concatenation example:
['moroabd' 'moikkaedf']


In [41]:
print(np.char.center("moro", 20, fillchar = "-"))

--------moro--------


In [43]:
print(np.char.capitalize("moro"))

Moro


In [44]:
print(np.char.title("moro tampere"))

Moro Tampere


In [45]:
print(np.char.upper("moro"))
print(np.char.lower("MORO"))

MORO
moro


In [46]:
print(np.char.split("moro tampere ja tulevaisuus"))

['moro', 'tampere', 'ja', 'tulevaisuus']


In [48]:
print(np.char.splitlines("moro\ntampere ja tulevaisuus"))

['moro', 'tampere ja tulevaisuus']


In [63]:
print(np.char.strip(['nina','admin','anaita'],'a'))

['nin' 'dmin' 'nait']


In [69]:
print(np.char.join([':','-'],['dmy','ymd']))

['d:m:y' 'y-m-d']


In [70]:
print(np.char.replace("olen hyvä tanssija", "olen", "olin"))

olin hyvä tanssija
