# DATA - Advanced Methods of Data Processing 
## Exercise: NumPy

In [1]:
## Your code here 
print("Exercise by: Janne Bragge")

Exercise by: Janne Bragge


### NumPy
Numpy is desiged to handle large multidimensional arrays and enable efficient computations with them. In the back, it runs pre-compiled C code which is much faster than, say, a Python for loop. In this Numpy tutorial, we will covered the basics of Numpy, numpy arrays, element-wise operations, matrices operations and generating random matrices, indexing, slicing and broadcasting, which are useful concepts that will be reused in Pandas.

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

In [2]:
# Instructions: 
# - Fill all part where you find "#your code here"
# - Remember to run all cells in order
# - Do no edit existing code
# - You can find correct answer below each Cell before you run it
# - Last code Cell checks your answers
# - Remember to SAVE your notebook before you return it.

# hint. You can use "Run" => "Run All Cells" command before you save and return your notebook. 

#### Import NumPy as np

In [3]:
## Task 1:
import numpy as np

### PART I

#### Create NumPy array (named as A1) of 10 zeros with data type 'int'
**Note.** Notice the difference between Numpy array `shape = (10,)` and Numpy array `shape = (1, 10)`. In the first one only array lenght is defined. In the second one array format (rows and columns) is also defined.   

In [4]:
## Task 2:
A1 = np.zeros((1,10), dtype=int) 

 

In [5]:
print(A1.shape)
A1

(1, 10)


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

#### Create NumPy array (named as B1) of 10 ones with data type 'float'
**Note.** Notice the difference between Numpy array `shape = (10,)` and Numpy array `shape = (1, 10)`. In the first one only array lenght is defined. In the second one array format (rows and columns) is also defined.   

In [6]:
## Task 3:
B1 = np.ones((1,10), dtype=float)  

 

In [7]:
print(B1.shape)
B1

(1, 10)


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### Create NumPy array (named as C1) of 10 fives with data type 'float'
**Note.** Notice the difference between Numpy array `shape = (10,)` and Numpy array `shape = (1, 10)`. In the first one only array lenght is defined. In the second one array format (rows and columns) is also defined.   

In [8]:
## Task 4:
C1 = np.full((1, 10), 5.0, dtype=float) 

 

In [9]:
print(C1.shape)
C1

(1, 10)


array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

#### Create NumPy array (named as D1) of the integers from 10 to 50

In [10]:
## Task 5:
D1 = np.arange(10,51)

 

In [11]:
D1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create NumPy array (named as E1) of all the even integers from 10 to 50

In [12]:
## Task 6:
E1 = np.arange(10, 51, 2)

 

In [13]:
E1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create NumPy 3x3 matrix (named as F1) with values ranging from 0 to 8

In [14]:
## Task 7:
F1 = np.arange(9).reshape(3,3) 

 

In [15]:
F1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create NumPy 3x3 identity matrix (named as G1)

In [16]:
## Task 8:
G1 = np.identity(3)

 

In [17]:
G1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number (named as H1) between 0 and 1

In [18]:
np.random.seed(2021) # Do not change

In [19]:
## Task 9:
H1 = np.random.rand(1)

 

In [20]:
H1

array([0.60597828])

#### Use NumPy to generate an array of 25 random numbers (named as I1) sampled from a standard normal distribution

In [21]:
np.random.seed(2021) # Do not change

In [22]:
## Task 10:
I1 = np.random.standard_normal(25) 

 

In [23]:
I1

array([ 1.48860905,  0.67601087, -0.41845137, -0.80652081,  0.55587583,
       -0.70550429,  1.13085826,  0.64500184,  0.10641374,  0.42215483,
        0.12420684, -0.83795346,  0.4090157 ,  0.10275122, -1.90772239,
        1.1002243 , -1.40232506, -0.22508127, -1.33620597,  0.30372151,
       -0.72015884,  2.5449146 ,  1.31729112,  0.0726303 , -0.25610814])

#### Create the following matrix (named as J1):

In [24]:
## Task 11:
J1 = np.arange(0.01, 1.01, 0.01).reshape(10, 10)

 

In [25]:
J1

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1 (named as K1):

In [26]:
## Task 12:
K1 = np.linspace(0,1,20) 

 

In [27]:
K1

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### PART II

### Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [28]:
# Do not change this code!

mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Write here code that uses slicing and reproduces following output (named as A2):
```python
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
````

In [29]:
## Task 13:
A2 = mat[2:5, 1:]

 

In [30]:
A2

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### Write here code that uses slicing and reproduces following output (named as B2):
```python
20
```

In [31]:
## Task 14:
B2 = mat[3,4]
 

In [32]:
B2

20

#### Write here code that uses slicing and reproduces following output (named as C2):
```python
array([[ 2],
       [ 7],
       [12]])
```
**Note.** You need to create here a column vector, not a row vector!

In [33]:
## Task 15:
C2 = mat[:3,1:2]

 

In [34]:
C2

array([[ 2],
       [ 7],
       [12]])

#### Write here code that uses slicing and reproduces following output (named as D2):
```python
array([21, 22, 23, 24, 25])
```

In [35]:
## Task 16:
D2 = mat[4, 0:]

 

In [36]:
D2

array([21, 22, 23, 24, 25])

#### Write here code that uses slicing and reproduces following output (named as E2):
```python
array([[16, 17, 18, 19, 20],
      [21, 22, 23, 24, 25]])
```

In [37]:
## Task 17:
E2 = mat[3:5, 0:5] 
 

In [38]:
E2

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### PART III

#### Get the sum of all the values in mat (named as A3)

In [39]:
## Task 18:
A3 = np.sum(mat)

 

In [40]:
A3

325

#### Get the standard deviation of the values in mat (named as B3)

In [41]:
## Task 19:
B3 = np.std(mat)
 

In [42]:
B3

7.211102550927978

#### Get the sum of all the columns in mat (named as C3)

In [43]:
## Task 20:
C3 = np.sum(mat, axis=0) 

 

In [44]:
C3

array([55, 60, 65, 70, 75])

### PART IV

### Matrix operations with 2 Matrices

Now do following with matrices mat1 and mat2.

In [45]:
# Do not change this code!

mat1 = np.arange(6).reshape(2,3)
mat2 = np.arange(1,7).reshape(2,3)
print(mat1)
print(mat2)

[[0 1 2]
 [3 4 5]]
[[1 2 3]
 [4 5 6]]


#### Add matrices mat1 and mat2 (named as A4)

In [46]:
## Task 21:
A4 = mat1 + mat2 

 

In [47]:
A4

array([[ 1,  3,  5],
       [ 7,  9, 11]])

#### Concatenate matrices mat1 and mat2 row wise (named as B4)

In [48]:
## Task 22:
B4 = np.concatenate((mat1, mat2), axis=0) 

 

In [49]:
B4

array([[0, 1, 2],
       [3, 4, 5],
       [1, 2, 3],
       [4, 5, 6]])

#### Concatenate matrices mat1 and mat2 column wise (named as C4)

In [50]:
## Task 23:
C4 = np.concatenate((mat1, mat2), axis=1) 

 

In [51]:
C4

array([[0, 1, 2, 1, 2, 3],
       [3, 4, 5, 4, 5, 6]])

#### Multiply matrix 'mat1' with number 5 and matrix 'mat2' witn number 3. Then add multiplication results (named as D4)

In [52]:
## Task 24:
D4 = (mat1 * 5) + (mat2 * 3) 

 

In [53]:
D4

array([[ 3, 11, 19],
       [27, 35, 43]])

#### Multiply matrices 'mat1' and 'mat2' element wise e.g. with command 'np.multiply()' (named as E4)

In [54]:
## Task 25:
E4 = np.multiply(mat1, mat2) 

 

In [55]:
E4

array([[ 0,  2,  6],
       [12, 20, 30]])

#### Do matrix multiplication with matrices 'mat1' and 'mat2' e.g. with command 'np.matmul()' (named as F4) 
***hint.*** You must first transpose matrix 'mat2'.

In [56]:
## Task 26:
mat2_t = np.transpose(mat2)


F4 = np.matmul(mat1, mat2_t) 

 

In [57]:
F4

array([[ 8, 17],
       [26, 62]])

### Check your answers by running following cell

In [58]:
# Do not change this code!

import sys
sys.path.insert(0, '../answers/data_numpy_answers/')
from data_numpy_check import check1, check2, check3, check4


print("PART I:")
correct1 = check1(A1, B1, C1, D1, E1, F1, G1, H1, I1, J1, K1)
print("Correct answers", correct1, "/ 11.")

print("PART II:")
correct2 = check2(A2, B2, C2, D2, E2)
print("Correct answers", correct2, "/ 5.")

print("PART III:")
correct3 = check3(A3, B3, C3)
print("Correct answers", correct3, "/ 3.")

print("PART IV:")
correct4 = check4(A4, B4, C4, D4, E4, F4)
print("Correct answers", correct4, "/ 6.")



PART I:
Correct answers 11 / 11.
PART II:
Correct answers 5 / 5.
PART III:
Correct answers 3 / 3.
PART IV:
Correct answers 6 / 6.


# Great Job!